### ISSUE TITLE
[Bug]: Arm64 build can't be started on Apple Silicon Mac

### ISSUE THREAD

**Issue by bjoernh** [GeekCornerGH/threema-for-desktop#87]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/GeekCornerGH/Threema-For-Desktop/blob/master/CONTRIBUTING.md) for this project.
- [X] I have searched the [issue tracker](https://www.github.com/GeekCornerGH/Threema-For-Desktop/issues) for an issue that matches the one I want to file, without success.

### Threema For Desktop version

2.2.0

### What operating system are you using?

macOS

### Operating System Version

Mac OS 11.6

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Threema For Desktop version

-

### Expected Behavior

App should be open after install

### Actual Behavior

App can't be start. Error Message:
“Threema For Desktop.app” is damaged and can’t be opened. You should move it to the Bin.

**Comment by GeekCornerGH** [comment]
Actually, I am pretty sure you can fix it by going `Settings > Security > General > Run `

**Comment by bjoernh** [comment]
The security Options are correct, I think...
<img width="730" alt="image" src="https://user-images.githubusercontent.com/506641/134860237-73f187fc-d43d-4b95-ae84-b0cf66309efa.png">

And the x86 build works fine with Rosetta2 emulation

**Comment by GeekCornerGH** [comment]
Actually, I don't know what is wrong. I use Windows and Linux. But I don't use mac usually

**Comment by GeekCornerGH** [comment]
I may try a workaround, may you tell me if it works? I will notify you  of course :)

**Comment by GeekCornerGH** [comment]
Hello @bjoernh can you try this build? https://github.com/GeekCornerGH/threema-for-desktop/actions/runs/1277214171

**Comment by bjoernh** [comment]
yeah, the universal bundled version from above works fine 😊

**Comment by GeekCornerGH** [comment]
Perfect thank you for testing, I will apply this in next patch.
Have a great day.
